name: Deploy to Skynet

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_LIVEPEER_API_KEY: ${{secrets.REACT_APP_LIVEPEER_API_KEY}}
      REACT_APP_MORALIS_APP_ID: ${{secrets.REACT_APP_MORALIS_APP_ID}}
      REACT_APP_MORALIS_SERVER_URL: ${{secrets.REACT_APP_MORALIS_SERVER_URL}}
      REACT_APP_NFT_STORAGE_API_KEY: ${{secrets.REACT_APP_NFT_STORAGE_API_KEY}}
      REACT_APP_BICONOMY_API_KEY:  ${{secrets.REACT_APP_BICONOMY_API_KEY}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17

      - run: npm ci
      - run: npm install
      - run:  npm install moralis
      - run: npm install react-moralis
      - run: npm install react-router-dom
      - run: npm run build

      - name: "Deploy to Skynet"
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.SKYNET_REGISTRY_SEED || '' }}
